name = "realtime-whiteboard" # 一个新名字
main = "src/index.js"
compatibility_date = "2024-05-01"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "ChatRoom" ]